steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/TeslaLord/project-management-tool-security.git']

#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'docker.io/teslalord/security:${_VERSION}', '.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'docker.io/teslalord/security:${_VERSION}']
  
#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - '${_CONTAINERNAME}=docker.io/teslalord/${_CONTAINERNAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
availableSecrets:
  secretManager:
  - versionName: projects/friendly-hangar-380200/secrets/docker-password/versions/1
    env: 'PASSWORD'
  - versionName: projects/friendly-hangar-380200/secrets/docker-username/versions/1
    env: 'USERNAME'
substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: my-first-project
    _ZONE: northamerica-northeast1
    _GKE_CLUSTER: elg5164-cluster
    
    #Repository Specific configuration. DevOps can change this settings
    _DEPLOYMENTNAME: security
    _CONTAINERNAME: security
    _REPO_NAME: project-management-tool-security
    
    # Developers ONLY change
    _VERSION: first
    
options:
    substitution_option: 'ALLOW_LOOSE'
